image:
  - Visual Studio 2019

stack: python 3

environment:
  PY_DIR: C:\Python37-x64

platform:
  - x64

branches:
  only:
    - master

skip_tags: true

install:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
  - cmd: pip install -r requirements.txt
  - cmd: pip freeze

build_script:
  - cmd: pyinstaller.exe -w src/launch.py
  - cmd: python makensis.py > install.nsi
  - cmd: makensis.exe install.nsi

artifacts:
  - path: '*.exe'
    name: myartifact

deploy:
  tag: $(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: bt06FOuVpHyB8zXIF1jQvTOPU1/7YGe+57IJvn/xn/YTdZxwYCNvYpF3IWQqTptv

  artifact: myartifact
  draft: false
  prerelease: false
  on:
    branch: master # release from master branch only
    # APPVEYOR_REPO_TAG: true # deploy on tag push only
